<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowingController;
use App\Http\Controllers\FineController;
use App\Http\Controllers\RequestController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Public routes
Route::get('/', [BookController::class, 'index'])->name('home');
Route::resource('books', BookController::class)->only(['index', 'show']);

// Auth routes (generated by Laravel Breeze)
require __DIR__.'/auth.php';

// Protected routes
Route::middleware('auth')->group(function () {
    // General dashboard route
    Route::get('dashboard', function () {
        return Auth::user()->isAdmin 
            ? redirect()->route('admin.dashboard')
            : redirect()->route('home');
    })->name('dashboard');

    // Borrowing routes
    Route::get('borrowings', [BorrowingController::class, 'index'])->name('borrowings.index');
    Route::post('books/{book}/borrow', [BorrowingController::class, 'borrow'])->name('books.borrow');
    Route::post('borrowings/{borrowing}/return', [BorrowingController::class, 'returnBook'])->name('borrowings.return');
    Route::post('borrowings/{borrowing}/renew', [BorrowingController::class, 'renew'])->name('borrowings.renew');

    // Request routes
    Route::get('requests', [RequestController::class, 'index'])->name('requests.index');
    Route::post('books/{book}/request', [RequestController::class, 'store'])->name('books.request');

    // Fine routes
    Route::get('fines', [FineController::class, 'index'])->name('fines.index');
    Route::post('fines/{fine}/pay', [FineController::class, 'pay'])->name('fines.pay');

    // Admin routes
    Route::middleware('admin')->group(function () {
        Route::get('admin', [DashboardController::class, 'index'])->name('admin.dashboard');
        
        // Test route for admin middleware
        Route::get('admin/test', function () {
            $user = Auth::user();
            return response()->json([
                'message' => 'Admin middleware is working!',
                'user' => [
                    'id' => $user->id,
                    'name' => $user->name,
                    'email' => $user->email
                ],
                'is_admin' => $user->isAdmin
            ]);
        })->name('admin.test');
        
        Route::resource('books', BookController::class)->except(['index', 'show']);
        Route::post('requests/{request}/approve', [RequestController::class, 'approve'])->name('requests.approve');
        Route::post('requests/{request}/reject', [RequestController::class, 'reject'])->name('requests.reject');
    });
});
